title: Henry Yuan He
position: Stats and Coding Enthusiast
affiliation: University of Oxford
email: yuan.he@st-hughs.ox.ac.uk
keywords: Henry 
google_scholar: https://scholar.google.com/
github_link: https://github.com/Henry-Yuan-He
linkedin: https://www.linkedin.com/in/henry-yuan-he
avatar: ./assets/img/He1.HEIC
google_analytics: UA-111540567-4
favicon: ./assets/img/MyPicture2.JPG
favicon_dark: ./assets/img/MyPicture2.JPG
description: Henry's academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
