title: He Yuan
position: Undergraduate Student
affiliation: National University of Singapore
email: he.yuan@u.nus.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/Henry-Yuan-He
linkedin: https://www.linkedin.com/in/henry-yuan-he-09212a165
avatar: ./assets/img/MyPicture.JPG
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
